seeker-time: 120 # zannina ricordati che non sono 120 minuti, sono 120 secondi.
# qui sopra quindi il tempo è in secondi, CAPITO??????????????????????????
# Sono matto, perciò vi faccio tutti i plugin che riesco :)

min-players: 4             # minimo giocatori per startare
pre-start-chat: true        # se true mostra countdown in chat
pre-start-time: 15          # secondi prima di dare inizio al gioco

lobby:
  world: world
  x: 0.0
  y: 64.0
  z: 0.0
  yaw: 0.0
  pitch: 0.0
  radius: 20.0             # raggio della lobby per evitare spawn troppo vicino
seeker-blind-time: 60       # secondi di blindness e "immobilità" iniziale per i seeker